version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-44-235-121.compute-1.amazonaws.com
            port: '5432'
            database: d8tfcr3kd8qm09
            ssl: true
            user: khaxjiggihvuvn
            password: 17ef245e41f7aa3ef4dd36fc6ccd85beaefd8176a80ab43ea62ac864a0d88833
            migrations: true